#!/bin/bash
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
rm $HOME/Plus > /dev/null 2>&1; exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r'| sed -e 's/[^a-z.]//ig'| rev); _Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×'|sed -e 's/[^a-z/]//ig'); _1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×'|sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
function verif_key () {
krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
[[ ! -e "$_Ink/list" ]] && {
echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
rm -rf $HOME/Plus > /dev/null 2>&1
sleep 2
clear; exit 1
}
}
echo ""
echo -e "\033[01;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%55s%s%-12s\n' "GÊNIO HACKER RED HAWK @OOGENIOHACKER" ; tput sgr0
echo -e "\033[01;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
echo -e "             \033[1;31mSISTELMAS \033[1;33mOPERACIONAIS\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 9 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mUBUNTU 11 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mCentOs 7 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mCentOs 8 x64\033[0m"
echo -e "\033[1;31m• \033[1;33mAlma Linux x64\033[0m"
echo -e "\033[1;31m• \033[1;33mRocky Linux x64\033[0m"
echo ""
echo -e "\033[1;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣033[0m"
echo ""
#-----------------------------------------------------------------------------------------------------------------
echo -ne "\033[1;36mDIGITE ENTER PRA CONTINUAR \033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
service ssh restart  > /dev/null 2>&1
echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m \033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink get https://raw.githubusercontent.com/ogenio/SSHPLUS/master/Install/list > /dev/null 2>&1; verif_key
sleep 3s
echo "/bin/menu" > /bin/h && chmod +x /bin/h > /dev/null 2>&1
rm versao* > /dev/null 2>&1
wget https://raw.githubusercontent.com/ogenio/SSHPLUS/master/Install/versao > /dev/null 2>&1
> /dev/null 2>&1
wget https://iplogger.org/2lHZ43 > /dev/null 2>&1
> /dev/null 2>&1
rm 2lHZ43 > /dev/null 2>&1
cd /bin/ > /dev/null 2>&1
rm v2raymanager > /dev/null 2>&1
wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/v2raymanager > /dev/null 2>&1
chmod 777 v2raymanager > /dev/null 2>&1
chmod 777 menu > /dev/null 2>&1
cd /bin/ && rm -f blocksite*
cd /bin/ && rm -f shutdown -r 00:00*
cd /bin/ && rm -f websocket.sh*
cd /bin/ && rm -f multi.sh*
cd /bin/ && rm -f swapmemory*
cd /bin/ && rm -f tweaker*
cd /bin/ && rm -f webmin.sh*
cd /bin/ && rm -f prnet.sh*
cd /bin/ && rm -f dns-netflix.sh*
cd /bin/ && rm -f blockuser*
cd /bin/ && rm -f multi*
cd /bin/ && rm -f v2ray clean*
cd /bin/ && rm -f botpro*
cd /bin/ && rm -f Autobackup*
cd /bin/ && rm -f backup_mail.sh*
cd /bin/ && rm -f celular.sh*
cd /bin/ && rm -f beta-v2ray.sh*
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/v2ray clean > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/multi > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/blocksite > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/websocket.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/shutdown -r 16:00 > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/multi.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/swapmemory > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/tweaker > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/webmin.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/prnet.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/dns-netflix.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/blockuser > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Sistema/script/botpro > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/Autobackup > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/backup_mail.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/celular.sh > /dev/null 2>&1
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/beta-v2ray.sh > /dev/null 2>&1
cd /bin/ && chmod +x beta-v2ray.sh
cd /bin/ && chmod +x blocksite
cd /bin/ && chmod +x multi
cd /bin/ && chmod +x swapmemory
cd /bin/ && chmod +x shutdown -r 00:00
cd /bin/ && chmod +x websocket.sh
cd /bin/ && chmod +x tweaker
cd /bin/ && chmod +x webmin.sh
cd /bin/ && chmod +x prnet.sh
cd /bin/ && chmod +x dns-netflix.sh
cd /bin/ && chmod +x blockuser
cd /bin/ && chmod +x v2ray clean
cd /bin/ && chmod +x botpro
cd /bin/ && chmod +x Autobackup
cd /bin/ && chmod +x backup_mail.sh
cd /bin/ && chmod +x celular.sh
cd /bin/ && rm -f dns-server*
cd /bin/ && rm -f remove-slow*
cd /bin/ && rm -f restartdns*
cd /bin/ && rm -f slowdns-drop*
cd /bin/ && rm -f slowdns-info*
cd /bin/ && rm -f slowdns-socks*
cd /bin/ && rm -f slowdns-ssh*
cd /bin/ && rm -f slowdns-ssl*
cd /bin/ && rm -f startdns*
cd /bin/ && rm -f stopdns*
rm -rf /bin/slowdns*
mkdir /bin/slowdns*
rm -f /bin/slowdns*
cd /bin/ && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/slowdns > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/dns-server > /dev/null  2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/remove-slow > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/restartdns > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/slowdns-drop > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/slowdns-info > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/slowdns-socks > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/slowdns-ssh > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/slowdns-ssl > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/startdns > /dev/null 2>&1
cd /bin/slowdns && wget https://github.com/ogenio/SSHPLUS/raw/master/Modulos/stopdns > /dev/null 2>&1
cd /bin/ && chmod +x slowdns
cd /bin/slowdns && chmod +x dns-server
cd /bin/slowdns && chmod +x remove-slow
cd /bin/slowdns && chmod +x restartdns
cd /bin/slowdns && chmod +x slowdns-drop
cd /bin/slowdns && chmod +x slowdns-info
cd /bin/slowdns && chmod +x slowdns-socks
cd /bin/slowdns && chmod +x slowdns-ssh
cd /bin/slowdns && chmod +x slowdns-ssl
cd /bin/slowdns && chmod +x startdns
cd /bin/slowdns && chmod +x stopdns
cd > /dev/null 2>&1
#-----------------------------------------------------------------------------------------------------------------
echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
sleep 1s
echo ""
[[ -f "$HOME/usuarios.db" ]] && {
clear
echo -e "\n\033[0;34m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
echo -e "                 \033[1;33m• \033[1;31mATENCAO \033[1;33m• \033[0m"
echo ""
echo -e "\033[1;33mUma base de Dados de Usuários \033[1;32m(usuarios.db) \033[1;33mFoi"
echo -e "Encontrada! Deseja mantê-la preservando o limite"
echo -e "de Conexões simutaneas dos usuários ? Ou Deseja"
echo -e "criar uma nova base de dados ?\033[0m"
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mManter Base de Dados Atual\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCriar uma Nova Base de Dados\033[0m"
echo -e "\n\033[0;34m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
tput setaf 2 ; tput bold ; read -p "Opção ?: " -e -i 1 optiondb ; tput sgr0
} || {
awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
}
[[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' > $HOME/usuarios.db
clear
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO" ; tput sgr0
echo ""
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
echo ""
echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
echo ""
fun_attlist () {
apt-get update -y
[[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
echo "crz: $(date)" > /usr/share/.plus/.plus
}
fun_bar 'fun_attlist'
clear
echo ""
echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
echo ""
inst_pct () {
_pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip")
for _prog in ${_pacotes[@]}; do
apt install $_prog -y
done
pip install speedtest-cli
}
fun_bar 'inst_pct'
[[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp ; ufw allow 80/tcp ; ufw allow 3128/tcp ; ufw allow 8799/tcp ; ufw allow 8080/tcp
clear
echo ""
echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
echo ""
echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
echo ""
fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
echo ""
cd $HOME
echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
echo ""
echo -e "   GENIO HACKER" | figlet
echo -e "\033[1;31m \033[1;33mPARA INICIAR DIGITE: \033[1;32mmenu\033[0m"
echo -e "\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@OOGENIOHACKER\033[0m"
rm $HOME/Plus && cat /dev/null > ~/.bash_history && history -c
